/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author holberton
 */
public class AdminVista extends javax.swing.JFrame {

    /**
     * Creates new form AdminVista
     */
    public AdminVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnelCrearPedido = new javax.swing.JPanel();
        tituloCrearPedido = new javax.swing.JLabel();
        labelMesas = new javax.swing.JLabel();
        labelProductos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdBtnMesa4 = new javax.swing.JRadioButton();
        rdBtnMesa1 = new javax.swing.JRadioButton();
        rdBtnMesa2 = new javax.swing.JRadioButton();
        rdBtnMesa3 = new javax.swing.JRadioButton();
        cbxEntradas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelProductos1 = new javax.swing.JLabel();
        labelProductos2 = new javax.swing.JLabel();
        labelProductos3 = new javax.swing.JLabel();
        labelProductos4 = new javax.swing.JLabel();
        labelProductos5 = new javax.swing.JLabel();
        cbxFritos = new javax.swing.JComboBox<>();
        cbxBebidas = new javax.swing.JComboBox<>();
        cbxEspeciales = new javax.swing.JComboBox<>();
        cbxSancocho = new javax.swing.JComboBox<>();
        cantBebidas = new javax.swing.JSpinner();
        cantEntradas = new javax.swing.JSpinner();
        cantSancocho = new javax.swing.JSpinner();
        cantEspeciales = new javax.swing.JSpinner();
        cantFritos = new javax.swing.JSpinner();
        btnCrearPedido = new javax.swing.JButton();
        pnelChat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEnviarChat = new javax.swing.JButton();
        btnIniciarChat = new javax.swing.JButton();
        btnCerrarChat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        pnelModificarPedido = new javax.swing.JPanel();
        tituloCrearPedido1 = new javax.swing.JLabel();
        labelMesas1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdBtnModificarMesa4 = new javax.swing.JRadioButton();
        rdBtnModificarMesa1 = new javax.swing.JRadioButton();
        rdBtnModificarMesa2 = new javax.swing.JRadioButton();
        rdBtnModificarMesa3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDetallePedidoMesa = new javax.swing.JTextArea();
        btnBuscarModificarPedido = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnModificarPedido = new javax.swing.JButton();
        pnelCerrarPedido = new javax.swing.JPanel();
        tituloCrearPedido2 = new javax.swing.JLabel();
        labelMesas2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rdBtnMesa5 = new javax.swing.JRadioButton();
        rdBtnMesa6 = new javax.swing.JRadioButton();
        rdBtnMesa7 = new javax.swing.JRadioButton();
        rdBtnMesa8 = new javax.swing.JRadioButton();
        btnCerrarPedido = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaDetallePedidoCerrar = new javax.swing.JTextArea();
        btnBuscarCerrarPedido1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 102, 0));
        titulo.setText("RESTAURANTE MESAMASTER");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 540, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnelCrearPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnelCrearPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido.setText("Crear Pedido");
        pnelCrearPedido.add(tituloCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 38));

        labelMesas.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelMesas.setText("Mesas: ");
        pnelCrearPedido.add(labelMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        labelProductos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos.setText("Especiales");
        pnelCrearPedido.add(labelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        pnelCrearPedido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        pnelCrearPedido.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        pnelCrearPedido.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 120));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        pnelCrearPedido.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 120));

        rdBtnMesa4.setText("Mesa #4");
        pnelCrearPedido.add(rdBtnMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        rdBtnMesa1.setText("Mesa #1");
        rdBtnMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMesa1ActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(rdBtnMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        rdBtnMesa2.setText("Mesa #2");
        pnelCrearPedido.add(rdBtnMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rdBtnMesa3.setText("Mesa #3");
        pnelCrearPedido.add(rdBtnMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        cbxEntradas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxEntradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tostadas $8.000", "Porción papas $8.000" }));
        cbxEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntradasActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tilapia Frita.png"))); // NOI18N
        pnelCrearPedido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seviche.png"))); // NOI18N
        pnelCrearPedido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sancocho.png"))); // NOI18N
        pnelCrearPedido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, 100));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot from 2024-12-08 03-40-19.png"))); // NOI18N
        pnelCrearPedido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 100, 130));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tilapia Frita.png"))); // NOI18N
        pnelCrearPedido.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 140));

        labelProductos1.setBackground(new java.awt.Color(255, 255, 255));
        labelProductos1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelProductos1.setText("Productos:");
        pnelCrearPedido.add(labelProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelProductos2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos2.setText("Fritos");
        pnelCrearPedido.add(labelProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        labelProductos3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos3.setText("Entradas");
        pnelCrearPedido.add(labelProductos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        labelProductos4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos4.setText("Sancochos");
        pnelCrearPedido.add(labelProductos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        labelProductos5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos5.setText("Bebidas");
        pnelCrearPedido.add(labelProductos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        cbxFritos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxFritos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tilapia $35.000", "Tilapia $20.000" }));
        cbxFritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFritosActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxFritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        cbxBebidas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limonada Natu $8.000", "Limonada Cere $10.000", "Limonada Coco $10.000" }));
        cbxBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBebidasActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        cbxEspeciales.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxEspeciales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caz. camarón $35.000", "Caz. mariscos $35.000", " " }));
        cbxEspeciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecialesActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, -1));

        cbxSancocho.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxSancocho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño $4.000", "Mediano $6.000", "Grande $8.000", " " }));
        cbxSancocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSancochoActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxSancocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        cantBebidas.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        cantEntradas.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        cantSancocho.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantSancocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));

        cantEspeciales.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        cantFritos.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantFritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        btnCrearPedido.setBackground(new java.awt.Color(255, 102, 0));
        btnCrearPedido.setFont(new java.awt.Font("Liberation Sans", 1, 26)); // NOI18N
        btnCrearPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPedido.setText("Crear ! ");
        btnCrearPedido.setBorder(null);
        btnCrearPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(btnCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 130, 70));

        jTabbedPane1.addTab("Crear Pedido", pnelCrearPedido);

        pnelChat.setBackground(new java.awt.Color(255, 255, 255));
        pnelChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Chat");
        pnelChat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        pnelChat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 690, 300));

        btnEnviarChat.setBackground(new java.awt.Color(255, 102, 0));
        btnEnviarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnEnviarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarChat.setText("Enviar");
        btnEnviarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnEnviarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 510, 190, -1));

        btnIniciarChat.setBackground(new java.awt.Color(255, 102, 0));
        btnIniciarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnIniciarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarChat.setText("Iniciar chat");
        btnIniciarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnIniciarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, -1));

        btnCerrarChat.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCerrarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarChat.setText("Cerrar chat");
        btnCerrarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnCerrarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 578, 160, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chat.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        pnelChat.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 220, 160));

        jTabbedPane1.addTab("Chat", pnelChat);

        pnelModificarPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnelModificarPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido1.setText("Modificar Pedido");
        pnelModificarPedido.add(tituloCrearPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 38));

        labelMesas1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelMesas1.setText("Mesas: ");
        pnelModificarPedido.add(labelMesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel11.setText("jLabel1");
        pnelModificarPedido.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 120));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel12.setText("jLabel1");
        pnelModificarPedido.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        pnelModificarPedido.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 120));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel14.setText("jLabel1");
        pnelModificarPedido.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 120));

        rdBtnModificarMesa4.setText("Mesa #4");
        pnelModificarPedido.add(rdBtnModificarMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        rdBtnModificarMesa1.setText("Mesa #1");
        rdBtnModificarMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnModificarMesa1ActionPerformed(evt);
            }
        });
        pnelModificarPedido.add(rdBtnModificarMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        rdBtnModificarMesa2.setText("Mesa #2");
        pnelModificarPedido.add(rdBtnModificarMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rdBtnModificarMesa3.setText("Mesa #3");
        pnelModificarPedido.add(rdBtnModificarMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        txtaDetallePedidoMesa.setColumns(20);
        txtaDetallePedidoMesa.setRows(5);
        jScrollPane2.setViewportView(txtaDetallePedidoMesa);

        pnelModificarPedido.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 720, 130));

        btnBuscarModificarPedido.setBackground(new java.awt.Color(255, 102, 0));
        btnBuscarModificarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnBuscarModificarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarModificarPedido.setText("Buscar");
        btnBuscarModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarPedidoActionPerformed(evt);
            }
        });
        pnelModificarPedido.add(btnBuscarModificarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel15.setText("Detalles de pedido:");
        pnelModificarPedido.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnModificarPedido.setBackground(new java.awt.Color(255, 0, 0));
        btnModificarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnModificarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPedido.setText("Modificar Pedido");
        btnModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPedidoActionPerformed(evt);
            }
        });
        pnelModificarPedido.add(btnModificarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 190, 50));

        jTabbedPane1.addTab("Modificar Pedido", pnelModificarPedido);

        pnelCerrarPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnelCerrarPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido2.setText("Cerrar Pedido");
        pnelCerrarPedido.add(tituloCrearPedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 38));

        labelMesas2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelMesas2.setText("Mesas: ");
        pnelCerrarPedido.add(labelMesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel16.setText("jLabel1");
        pnelCerrarPedido.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 120));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel17.setText("jLabel1");
        pnelCerrarPedido.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel18.setText("jLabel1");
        pnelCerrarPedido.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 120));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel19.setText("jLabel1");
        pnelCerrarPedido.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 120));

        rdBtnMesa5.setText("Mesa #4");
        pnelCerrarPedido.add(rdBtnMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        rdBtnMesa6.setText("Mesa #1");
        rdBtnMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMesa6ActionPerformed(evt);
            }
        });
        pnelCerrarPedido.add(rdBtnMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        rdBtnMesa7.setText("Mesa #2");
        pnelCerrarPedido.add(rdBtnMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rdBtnMesa8.setText("Mesa #3");
        pnelCerrarPedido.add(rdBtnMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btnCerrarPedido.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCerrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarPedido.setText("Cerrar Pedido");
        btnCerrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarPedidoActionPerformed(evt);
            }
        });
        pnelCerrarPedido.add(btnCerrarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 190, 50));

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel20.setText("Detalles de pedido:");
        pnelCerrarPedido.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtaDetallePedidoCerrar.setColumns(20);
        txtaDetallePedidoCerrar.setRows(5);
        jScrollPane3.setViewportView(txtaDetallePedidoCerrar);

        pnelCerrarPedido.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 720, 130));

        btnBuscarCerrarPedido1.setBackground(new java.awt.Color(255, 102, 0));
        btnBuscarCerrarPedido1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnBuscarCerrarPedido1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCerrarPedido1.setText("Buscar");
        btnBuscarCerrarPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCerrarPedido1ActionPerformed(evt);
            }
        });
        pnelCerrarPedido.add(btnBuscarCerrarPedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jTabbedPane1.addTab("Cerrar Pedido", pnelCerrarPedido);

        Background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnMesa1ActionPerformed

    private void cbxEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntradasActionPerformed

    private void cbxFritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFritosActionPerformed

    private void cbxBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBebidasActionPerformed

    private void cbxEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspecialesActionPerformed

    private void cbxSancochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSancochoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSancochoActionPerformed

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        //MeseroControl.crearPedido();
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarChatActionPerformed

    private void btnIniciarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarChatActionPerformed

    private void btnCerrarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarChatActionPerformed

    private void rdBtnModificarMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnModificarMesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnModificarMesa1ActionPerformed

    private void btnBuscarModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarModificarPedidoActionPerformed

    private void btnModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPedidoActionPerformed

    private void rdBtnMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMesa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnMesa6ActionPerformed

    private void btnCerrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarPedidoActionPerformed

    private void btnBuscarCerrarPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCerrarPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCerrarPedido1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBuscarCerrarPedido1;
    private javax.swing.JButton btnBuscarModificarPedido;
    private javax.swing.JButton btnCerrarChat;
    private javax.swing.JButton btnCerrarPedido;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JButton btnEnviarChat;
    private javax.swing.JButton btnIniciarChat;
    private javax.swing.JButton btnModificarPedido;
    private javax.swing.JSpinner cantBebidas;
    private javax.swing.JSpinner cantEntradas;
    private javax.swing.JSpinner cantEspeciales;
    private javax.swing.JSpinner cantFritos;
    private javax.swing.JSpinner cantSancocho;
    private javax.swing.JComboBox<String> cbxBebidas;
    private javax.swing.JComboBox<String> cbxEntradas;
    private javax.swing.JComboBox<String> cbxEspeciales;
    private javax.swing.JComboBox<String> cbxFritos;
    private javax.swing.JComboBox<String> cbxSancocho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelMesas;
    private javax.swing.JLabel labelMesas1;
    private javax.swing.JLabel labelMesas2;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelProductos1;
    private javax.swing.JLabel labelProductos2;
    private javax.swing.JLabel labelProductos3;
    private javax.swing.JLabel labelProductos4;
    private javax.swing.JLabel labelProductos5;
    private javax.swing.JPanel pnelCerrarPedido;
    private javax.swing.JPanel pnelChat;
    private javax.swing.JPanel pnelCrearPedido;
    private javax.swing.JPanel pnelModificarPedido;
    private javax.swing.JRadioButton rdBtnMesa1;
    private javax.swing.JRadioButton rdBtnMesa2;
    private javax.swing.JRadioButton rdBtnMesa3;
    private javax.swing.JRadioButton rdBtnMesa4;
    private javax.swing.JRadioButton rdBtnMesa5;
    private javax.swing.JRadioButton rdBtnMesa6;
    private javax.swing.JRadioButton rdBtnMesa7;
    private javax.swing.JRadioButton rdBtnMesa8;
    private javax.swing.JRadioButton rdBtnModificarMesa1;
    private javax.swing.JRadioButton rdBtnModificarMesa2;
    private javax.swing.JRadioButton rdBtnModificarMesa3;
    private javax.swing.JRadioButton rdBtnModificarMesa4;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloCrearPedido;
    private javax.swing.JLabel tituloCrearPedido1;
    private javax.swing.JLabel tituloCrearPedido2;
    private javax.swing.JTextArea txtaDetallePedidoCerrar;
    private javax.swing.JTextArea txtaDetallePedidoMesa;
    // End of variables declaration//GEN-END:variables
}
