/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author holberton
 */
public class AdminVista extends javax.swing.JFrame {

    /**
     * Creates new form AdminVista
     */
    public AdminVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnelResumenVentas = new javax.swing.JPanel();
        tituloResumenVentas = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cbxRangoFecha = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtaProductosVendidos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaProductosVendidos1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtaBusquedaFiltrada = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxMeseroBusqueda = new javax.swing.JComboBox<>();
        cbxProductoBusqueda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnelGestionUsuarios = new javax.swing.JPanel();
        tituloGestionUsuarios = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaResultadoEliminarUsuario = new javax.swing.JTextArea();
        btnListarUsuarios = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnEditarUsuario = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCrearUsuario = new javax.swing.JTextField();
        txtEditarNombreUsuario = new javax.swing.JTextField();
        cbxCrearRolUsuario = new javax.swing.JComboBox<>();
        cbxCrearEstadoUsuario = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        txtCrearNombreCompleto = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtaListaUsuarios = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtaResultadoEditarUsuario = new javax.swing.JTextArea();
        txtEliminarUsuario = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnBuscarUsuarioEliminar = new javax.swing.JButton();
        btnBuscarNombreUsuarioEditar1 = new javax.swing.JButton();
        pnelGestionMesas = new javax.swing.JPanel();
        tituloCrearPedido2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnCrearMesa = new javax.swing.JButton();
        btnEditarMesa = new javax.swing.JButton();
        btnEliminarMesa = new javax.swing.JButton();
        btnListarMesas = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtaListaMesas = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCrearNombreMesa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxCrearEstadoMesa = new javax.swing.JComboBox<>();
        cbxCrearUbicacionMesa = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        cbxCrearCapacidadMesa = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        txtEditarNombreMesa = new javax.swing.JTextField();
        btnBuscarNombreMesaEditar = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtaResultadoEditarMesa = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtEliminarNombreMesa = new javax.swing.JTextField();
        btnBuscarNombreMesaEliminar = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtaResultadoEliminarMesa = new javax.swing.JTextArea();
        pnelGestionProductos = new javax.swing.JPanel();
        tituloCrearPedido3 = new javax.swing.JLabel();
        btnCrearProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnListarProductos = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtaListaProductos = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtCrearPrecioProducto = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cbxCrearEstadoProducto = new javax.swing.JComboBox<>();
        cbxCrearImagenProducto = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        txtEditarNombreProducto = new javax.swing.JTextField();
        btnBuscarNombreProductoEditar = new javax.swing.JButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtaResultadoEditarProducto = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtEliminarNombreProducto = new javax.swing.JTextField();
        btnBuscarNombreProductoEliminar = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtaResultadoEliminarProducto = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        txtCrearNombreProducto1 = new javax.swing.JTextField();
        pnelPedidosenCurso = new javax.swing.JPanel();
        tituloCrearPedido4 = new javax.swing.JLabel();
        labelMesas4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rdBtnMesa13 = new javax.swing.JRadioButton();
        rdBtnMesa14 = new javax.swing.JRadioButton();
        rdBtnMesa15 = new javax.swing.JRadioButton();
        rdBtnMesa16 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaDetallePedidoCerrar2 = new javax.swing.JTextArea();
        btnBuscarCerrarPedido3 = new javax.swing.JButton();
        pnelChat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEnviarChat = new javax.swing.JButton();
        btnIniciarChat = new javax.swing.JButton();
        btnCerrarChat = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 102, 0));
        titulo.setText("RESTAURANTE MESAMASTER");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 540, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnelResumenVentas.setBackground(new java.awt.Color(255, 255, 255));
        pnelResumenVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloResumenVentas.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloResumenVentas.setText("Resumen de Ventas");
        pnelResumenVentas.add(tituloResumenVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 38));

        jLabel32.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel32.setText("Fecha:");
        pnelResumenVentas.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        cbxRangoFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Semana", "Mes", "Año" }));
        cbxRangoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRangoFechaActionPerformed(evt);
            }
        });
        pnelResumenVentas.add(cbxRangoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        txtaProductosVendidos.setColumns(20);
        txtaProductosVendidos.setRows(5);
        jScrollPane6.setViewportView(txtaProductosVendidos);

        pnelResumenVentas.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 320, 40));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Total de Ventas:");
        pnelResumenVentas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Productos vendidos:");
        pnelResumenVentas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtaProductosVendidos1.setColumns(20);
        txtaProductosVendidos1.setRows(5);
        jScrollPane7.setViewportView(txtaProductosVendidos1);

        pnelResumenVentas.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, 170));
        pnelResumenVentas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 340, -1));

        txtaBusquedaFiltrada.setColumns(20);
        txtaBusquedaFiltrada.setRows(5);
        jScrollPane8.setViewportView(txtaBusquedaFiltrada);

        pnelResumenVentas.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 670, 130));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Busqueda filtrada");
        pnelResumenVentas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel5.setText("Mesero:");
        pnelResumenVentas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        jLabel6.setText("Producto:");
        pnelResumenVentas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        cbxMeseroBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stephany", "Gean", "Alexis", " ", " " }));
        pnelResumenVentas.add(cbxMeseroBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 150, -1));

        cbxProductoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entradas", "Especiales", "Fritos", "Bebidas", "Sancochos" }));
        pnelResumenVentas.add(cbxProductoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, -1));

        jLabel7.setText("jLabel7");
        pnelResumenVentas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 60));

        jLabel8.setText("jLabel7");
        pnelResumenVentas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 100, 60));

        jTabbedPane1.addTab("Resumen de Ventas", pnelResumenVentas);

        pnelGestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        pnelGestionUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloGestionUsuarios.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloGestionUsuarios.setText("Gestión de Usuarios");
        pnelGestionUsuarios.add(tituloGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 38));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel10.setText("Lista de Usuarios:");
        pnelGestionUsuarios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        txtaResultadoEliminarUsuario.setColumns(20);
        txtaResultadoEliminarUsuario.setRows(5);
        jScrollPane2.setViewportView(txtaResultadoEliminarUsuario);

        pnelGestionUsuarios.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 530, 50));

        btnListarUsuarios.setBackground(new java.awt.Color(255, 102, 0));
        btnListarUsuarios.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnListarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnListarUsuarios.setText("Usuarios");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });
        pnelGestionUsuarios.add(btnListarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 40));

        btnCrearUsuario.setBackground(new java.awt.Color(255, 102, 0));
        btnCrearUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setText("Crear");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        pnelGestionUsuarios.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 40));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel15.setText("Crear Usuario:");
        pnelGestionUsuarios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnEditarUsuario.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });
        pnelGestionUsuarios.add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 40));

        jLabel33.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel33.setText("Editar Usuario:");
        pnelGestionUsuarios.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        btnEliminarUsuario.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        pnelGestionUsuarios.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 110, 40));

        jLabel34.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel34.setText("Eliminar Usuario:");
        pnelGestionUsuarios.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        jLabel9.setText("Usuario:");
        pnelGestionUsuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));
        pnelGestionUsuarios.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jLabel12.setText("Nombre completo:");
        pnelGestionUsuarios.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel13.setText("Rol:");
        pnelGestionUsuarios.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel14.setText("Estado:");
        pnelGestionUsuarios.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        txtCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearUsuarioActionPerformed(evt);
            }
        });
        pnelGestionUsuarios.add(txtCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, -1));
        pnelGestionUsuarios.add(txtEditarNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 200, -1));

        cbxCrearRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Mesero" }));
        pnelGestionUsuarios.add(cbxCrearRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        cbxCrearEstadoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));
        pnelGestionUsuarios.add(cbxCrearEstadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        jLabel35.setText("Nombre completo:");
        pnelGestionUsuarios.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));
        pnelGestionUsuarios.add(txtCrearNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, -1));

        txtaListaUsuarios.setColumns(20);
        txtaListaUsuarios.setRows(5);
        jScrollPane9.setViewportView(txtaListaUsuarios);

        pnelGestionUsuarios.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 530, 100));

        txtaResultadoEditarUsuario.setColumns(20);
        txtaResultadoEditarUsuario.setRows(5);
        jScrollPane10.setViewportView(txtaResultadoEditarUsuario);

        pnelGestionUsuarios.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 530, 50));
        pnelGestionUsuarios.add(txtEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 200, -1));

        jLabel36.setText("Usuario:");
        pnelGestionUsuarios.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        btnBuscarUsuarioEliminar.setText("...");
        pnelGestionUsuarios.add(btnBuscarUsuarioEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        btnBuscarNombreUsuarioEditar1.setText("...");
        pnelGestionUsuarios.add(btnBuscarNombreUsuarioEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jTabbedPane1.addTab("Gestión de Usuarios", pnelGestionUsuarios);

        pnelGestionMesas.setBackground(new java.awt.Color(255, 255, 255));
        pnelGestionMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido2.setText("Gestión de Mesas");
        pnelGestionMesas.add(tituloCrearPedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 38));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel16.setText("jLabel1");
        pnelGestionMesas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 120, 120));

        btnCrearMesa.setBackground(new java.awt.Color(255, 102, 0));
        btnCrearMesa.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCrearMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearMesa.setText("Crear");
        btnCrearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMesaActionPerformed(evt);
            }
        });
        pnelGestionMesas.add(btnCrearMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 40));

        btnEditarMesa.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarMesa.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEditarMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMesa.setText("Editar");
        btnEditarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMesaActionPerformed(evt);
            }
        });
        pnelGestionMesas.add(btnEditarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, 40));

        btnEliminarMesa.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarMesa.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEliminarMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMesa.setText("Eliminar");
        btnEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMesaActionPerformed(evt);
            }
        });
        pnelGestionMesas.add(btnEliminarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 110, 40));

        btnListarMesas.setBackground(new java.awt.Color(255, 102, 0));
        btnListarMesas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnListarMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnListarMesas.setText("Mesas");
        btnListarMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarMesasActionPerformed(evt);
            }
        });
        pnelGestionMesas.add(btnListarMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 40));

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel20.setText("Editar Mesa:");
        pnelGestionMesas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        txtaListaMesas.setColumns(20);
        txtaListaMesas.setRows(5);
        jScrollPane11.setViewportView(txtaListaMesas);

        pnelGestionMesas.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 530, 100));

        jLabel37.setText("Nombre Mesa:");
        pnelGestionMesas.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel17.setText("Capacidad:");
        pnelGestionMesas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));
        pnelGestionMesas.add(txtCrearNombreMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 20));

        jLabel18.setText("Estado:");
        pnelGestionMesas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel19.setText("Ubicación:");
        pnelGestionMesas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        cbxCrearEstadoMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Ocupada", " " }));
        pnelGestionMesas.add(cbxCrearEstadoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, 20));

        cbxCrearUbicacionMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salón Principal", "Salón Medio", "Salón Pequeño" }));
        pnelGestionMesas.add(cbxCrearUbicacionMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 20));

        jLabel38.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel38.setText("Descripción de Mesas:");
        pnelGestionMesas.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        cbxCrearCapacidadMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "10" }));
        pnelGestionMesas.add(cbxCrearCapacidadMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 50, 20));

        jLabel39.setText("Nombre Mesa:");
        pnelGestionMesas.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));
        pnelGestionMesas.add(txtEditarNombreMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 200, 20));

        btnBuscarNombreMesaEditar.setText("...");
        pnelGestionMesas.add(btnBuscarNombreMesaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        txtaResultadoEditarMesa.setColumns(20);
        txtaResultadoEditarMesa.setRows(5);
        jScrollPane12.setViewportView(txtaResultadoEditarMesa);

        pnelGestionMesas.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 530, 50));

        jLabel40.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel40.setText("Crear Mesa:");
        pnelGestionMesas.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel41.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel41.setText("Eliminar Mesa:");
        pnelGestionMesas.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        jLabel42.setText("Nombre Mesa:");
        pnelGestionMesas.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));
        pnelGestionMesas.add(txtEliminarNombreMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 200, 20));

        btnBuscarNombreMesaEliminar.setText("...");
        pnelGestionMesas.add(btnBuscarNombreMesaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        txtaResultadoEliminarMesa.setColumns(20);
        txtaResultadoEliminarMesa.setRows(5);
        jScrollPane13.setViewportView(txtaResultadoEliminarMesa);

        pnelGestionMesas.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 530, 50));

        jTabbedPane1.addTab("Gestión de Mesas", pnelGestionMesas);

        pnelGestionProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnelGestionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido3.setText("Gestión de Productos");
        pnelGestionProductos.add(tituloCrearPedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 38));

        btnCrearProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnCrearProducto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCrearProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProducto.setText("Crear");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(btnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 40));

        btnEditarProducto.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarProducto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProducto.setText("Editar");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, 40));

        btnEliminarProducto.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarProducto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 110, 40));

        btnListarProductos.setBackground(new java.awt.Color(255, 102, 0));
        btnListarProductos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnListarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnListarProductos.setText("Productos");
        btnListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductosActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(btnListarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 40));

        jLabel43.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel43.setText("Editar Mesa:");
        pnelGestionProductos.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        txtaListaProductos.setColumns(20);
        txtaListaProductos.setRows(5);
        jScrollPane14.setViewportView(txtaListaProductos);

        pnelGestionProductos.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 530, 100));

        jLabel44.setText("Nombre Producto:");
        pnelGestionProductos.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel45.setText("Precio:");
        pnelGestionProductos.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        txtCrearPrecioProducto.setText("$");
        txtCrearPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearPrecioProductoActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(txtCrearPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 80, 20));

        jLabel46.setText("Estado:");
        pnelGestionProductos.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel47.setText("Imagen:");
        pnelGestionProductos.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        cbxCrearEstadoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));
        pnelGestionProductos.add(cbxCrearEstadoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, 20));

        cbxCrearImagenProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Aplica", " " }));
        pnelGestionProductos.add(cbxCrearImagenProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 20));

        jLabel48.setText("Nombre Producto:");
        pnelGestionProductos.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));
        pnelGestionProductos.add(txtEditarNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 200, 20));

        btnBuscarNombreProductoEditar.setText("...");
        pnelGestionProductos.add(btnBuscarNombreProductoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        txtaResultadoEditarProducto.setColumns(20);
        txtaResultadoEditarProducto.setRows(5);
        jScrollPane15.setViewportView(txtaResultadoEditarProducto);

        pnelGestionProductos.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 530, 50));

        jLabel49.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel49.setText("Crear Producto:");
        pnelGestionProductos.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel50.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel50.setText("Eliminar Mesa:");
        pnelGestionProductos.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        jLabel51.setText("Nombre Producto:");
        pnelGestionProductos.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, -1));
        pnelGestionProductos.add(txtEliminarNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 200, 20));

        btnBuscarNombreProductoEliminar.setText("...");
        pnelGestionProductos.add(btnBuscarNombreProductoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        txtaResultadoEliminarProducto.setColumns(20);
        txtaResultadoEliminarProducto.setRows(5);
        jScrollPane16.setViewportView(txtaResultadoEliminarProducto);

        pnelGestionProductos.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 530, 50));

        jLabel52.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel52.setText("Descripción de Productos:");
        pnelGestionProductos.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        txtCrearNombreProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearNombreProducto1ActionPerformed(evt);
            }
        });
        pnelGestionProductos.add(txtCrearNombreProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 200, 20));

        jTabbedPane1.addTab("Gestión de Productos", pnelGestionProductos);

        pnelPedidosenCurso.setBackground(new java.awt.Color(255, 255, 255));
        pnelPedidosenCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido4.setText("Pedidos en Curso");
        pnelPedidosenCurso.add(tituloCrearPedido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 38));

        labelMesas4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelMesas4.setText("Mesas: ");
        pnelPedidosenCurso.add(labelMesas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel27.setText("jLabel1");
        pnelPedidosenCurso.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 120));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel28.setText("jLabel1");
        pnelPedidosenCurso.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel29.setText("jLabel1");
        pnelPedidosenCurso.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 120));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel30.setText("jLabel1");
        pnelPedidosenCurso.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 120));

        rdBtnMesa13.setText("Mesa #4");
        pnelPedidosenCurso.add(rdBtnMesa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        rdBtnMesa14.setText("Mesa #1");
        rdBtnMesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMesa14ActionPerformed(evt);
            }
        });
        pnelPedidosenCurso.add(rdBtnMesa14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        rdBtnMesa15.setText("Mesa #2");
        pnelPedidosenCurso.add(rdBtnMesa15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rdBtnMesa16.setText("Mesa #3");
        pnelPedidosenCurso.add(rdBtnMesa16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel31.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel31.setText("Detalles de pedido:");
        pnelPedidosenCurso.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtaDetallePedidoCerrar2.setColumns(20);
        txtaDetallePedidoCerrar2.setRows(5);
        jScrollPane5.setViewportView(txtaDetallePedidoCerrar2);

        pnelPedidosenCurso.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 720, 130));

        btnBuscarCerrarPedido3.setBackground(new java.awt.Color(255, 102, 0));
        btnBuscarCerrarPedido3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnBuscarCerrarPedido3.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCerrarPedido3.setText("Buscar");
        btnBuscarCerrarPedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCerrarPedido3ActionPerformed(evt);
            }
        });
        pnelPedidosenCurso.add(btnBuscarCerrarPedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jTabbedPane1.addTab("Pedidos en curso", pnelPedidosenCurso);

        pnelChat.setBackground(new java.awt.Color(255, 255, 255));
        pnelChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Chat");
        pnelChat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        pnelChat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 690, 300));

        btnEnviarChat.setBackground(new java.awt.Color(255, 102, 0));
        btnEnviarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnEnviarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarChat.setText("Enviar");
        btnEnviarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnEnviarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 510, 190, -1));

        btnIniciarChat.setBackground(new java.awt.Color(255, 102, 0));
        btnIniciarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnIniciarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarChat.setText("Iniciar chat");
        btnIniciarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnIniciarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 170, -1));

        btnCerrarChat.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarChat.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnCerrarChat.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarChat.setText("Cerrar chat");
        btnCerrarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarChatActionPerformed(evt);
            }
        });
        pnelChat.add(btnCerrarChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 578, 160, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chat.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        pnelChat.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 220, 160));

        jTabbedPane1.addTab("Chat", pnelChat);

        Background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarChatActionPerformed

    private void btnIniciarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarChatActionPerformed

    private void btnEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarChatActionPerformed

    private void rdBtnMesa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMesa14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnMesa14ActionPerformed

    private void btnBuscarCerrarPedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCerrarPedido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCerrarPedido3ActionPerformed

    private void cbxRangoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRangoFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRangoFechaActionPerformed

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void txtCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearUsuarioActionPerformed

    private void btnCrearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMesaActionPerformed

    private void btnEditarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMesaActionPerformed

    private void btnEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMesaActionPerformed

    private void btnListarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarMesasActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarProductosActionPerformed

    private void txtCrearPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearPrecioProductoActionPerformed

    private void txtCrearNombreProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearNombreProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrearNombreProducto1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBuscarCerrarPedido3;
    private javax.swing.JButton btnBuscarNombreMesaEditar;
    private javax.swing.JButton btnBuscarNombreMesaEliminar;
    private javax.swing.JButton btnBuscarNombreProductoEditar;
    private javax.swing.JButton btnBuscarNombreProductoEliminar;
    private javax.swing.JButton btnBuscarNombreUsuarioEditar1;
    private javax.swing.JButton btnBuscarUsuarioEliminar;
    private javax.swing.JButton btnCerrarChat;
    private javax.swing.JButton btnCrearMesa;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEditarMesa;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarMesa;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnEnviarChat;
    private javax.swing.JButton btnIniciarChat;
    private javax.swing.JButton btnListarMesas;
    private javax.swing.JButton btnListarProductos;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JComboBox<String> cbxCrearCapacidadMesa;
    private javax.swing.JComboBox<String> cbxCrearEstadoMesa;
    private javax.swing.JComboBox<String> cbxCrearEstadoProducto;
    private javax.swing.JComboBox<String> cbxCrearEstadoUsuario;
    private javax.swing.JComboBox<String> cbxCrearImagenProducto;
    private javax.swing.JComboBox<String> cbxCrearRolUsuario;
    private javax.swing.JComboBox<String> cbxCrearUbicacionMesa;
    private javax.swing.JComboBox<String> cbxMeseroBusqueda;
    private javax.swing.JComboBox<String> cbxProductoBusqueda;
    private javax.swing.JComboBox<String> cbxRangoFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelMesas4;
    private javax.swing.JPanel pnelChat;
    private javax.swing.JPanel pnelGestionMesas;
    private javax.swing.JPanel pnelGestionProductos;
    private javax.swing.JPanel pnelGestionUsuarios;
    private javax.swing.JPanel pnelPedidosenCurso;
    private javax.swing.JPanel pnelResumenVentas;
    private javax.swing.JRadioButton rdBtnMesa13;
    private javax.swing.JRadioButton rdBtnMesa14;
    private javax.swing.JRadioButton rdBtnMesa15;
    private javax.swing.JRadioButton rdBtnMesa16;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloCrearPedido2;
    private javax.swing.JLabel tituloCrearPedido3;
    private javax.swing.JLabel tituloCrearPedido4;
    private javax.swing.JLabel tituloGestionUsuarios;
    private javax.swing.JLabel tituloResumenVentas;
    private javax.swing.JTextField txtCrearNombreCompleto;
    private javax.swing.JTextField txtCrearNombreMesa;
    private javax.swing.JTextField txtCrearNombreProducto1;
    private javax.swing.JTextField txtCrearPrecioProducto;
    private javax.swing.JTextField txtCrearUsuario;
    private javax.swing.JTextField txtEditarNombreMesa;
    private javax.swing.JTextField txtEditarNombreProducto;
    private javax.swing.JTextField txtEditarNombreUsuario;
    private javax.swing.JTextField txtEliminarNombreMesa;
    private javax.swing.JTextField txtEliminarNombreProducto;
    private javax.swing.JTextField txtEliminarUsuario;
    private javax.swing.JTextArea txtaBusquedaFiltrada;
    private javax.swing.JTextArea txtaDetallePedidoCerrar2;
    private javax.swing.JTextArea txtaListaMesas;
    private javax.swing.JTextArea txtaListaProductos;
    private javax.swing.JTextArea txtaListaUsuarios;
    private javax.swing.JTextArea txtaProductosVendidos;
    private javax.swing.JTextArea txtaProductosVendidos1;
    private javax.swing.JTextArea txtaResultadoEditarMesa;
    private javax.swing.JTextArea txtaResultadoEditarProducto;
    private javax.swing.JTextArea txtaResultadoEditarUsuario;
    private javax.swing.JTextArea txtaResultadoEliminarMesa;
    private javax.swing.JTextArea txtaResultadoEliminarProducto;
    private javax.swing.JTextArea txtaResultadoEliminarUsuario;
    // End of variables declaration//GEN-END:variables
}
