/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.MeseroControlador;
import Modelo.Pedido;
import Modelo.Producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;

/**
 *
 * @author holberton
 */
public class MeseroVista extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MeseroVista
     */
    private JLabel lblTotal;
    private MeseroControlador meseroControlador;
    
    public MeseroVista() {
        initComponents();
        ButtonGroup mesaGroup = new ButtonGroup();
        mesaGroup.add(rdBtnMesa1);
        mesaGroup.add(rdBtnMesa2);
        mesaGroup.add(rdBtnMesa3);
        mesaGroup.add(rdBtnMesa4);
        this.meseroControlador = meseroControlador;
        btnCrearPedido.addActionListener(this);
        //btnCrearPedido.addActionListener(e -> meseroControlador.crearPedido());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnelCrearPedido = new javax.swing.JPanel();
        tituloCrearPedido = new javax.swing.JLabel();
        labelMesas = new javax.swing.JLabel();
        labelProductos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdBtnMesa4 = new javax.swing.JRadioButton();
        rdBtnMesa1 = new javax.swing.JRadioButton();
        rdBtnMesa2 = new javax.swing.JRadioButton();
        rdBtnMesa3 = new javax.swing.JRadioButton();
        cbxEntradas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelProductos1 = new javax.swing.JLabel();
        labelProductos2 = new javax.swing.JLabel();
        labelProductos3 = new javax.swing.JLabel();
        labelProductos4 = new javax.swing.JLabel();
        labelProductos5 = new javax.swing.JLabel();
        cbxFritos = new javax.swing.JComboBox<>();
        cbxBebidas = new javax.swing.JComboBox<>();
        cbxEspeciales = new javax.swing.JComboBox<>();
        cbxSancocho = new javax.swing.JComboBox<>();
        cantBebidas = new javax.swing.JSpinner();
        cantEntradas = new javax.swing.JSpinner();
        cantSancocho = new javax.swing.JSpinner();
        cantEspeciales = new javax.swing.JSpinner();
        cantFritos = new javax.swing.JSpinner();
        btnCrearPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 102, 0));
        titulo.setText("RESTAURANTE MESAMASTER");
        titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 540, -1));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver Pedidos", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cerrar Pedidos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Resumen Ventas", jPanel4);

        pnelCrearPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnelCrearPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloCrearPedido.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloCrearPedido.setText("Crear Pedido");
        pnelCrearPedido.add(tituloCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 38));

        labelMesas.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelMesas.setText("Mesas: ");
        pnelCrearPedido.add(labelMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        labelProductos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos.setText("Especiales");
        pnelCrearPedido.add(labelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        pnelCrearPedido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, 120));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        pnelCrearPedido.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        pnelCrearPedido.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 120));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mesas.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        pnelCrearPedido.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 120, 120));

        rdBtnMesa4.setText("Mesa #4");
        pnelCrearPedido.add(rdBtnMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        rdBtnMesa1.setText("Mesa #1");
        rdBtnMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMesa1ActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(rdBtnMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        rdBtnMesa2.setText("Mesa #2");
        pnelCrearPedido.add(rdBtnMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        rdBtnMesa3.setText("Mesa #3");
        pnelCrearPedido.add(rdBtnMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        cbxEntradas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxEntradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tostadas $8.000", "Porción papas $8.000" }));
        cbxEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntradasActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tilapia Frita.png"))); // NOI18N
        pnelCrearPedido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seviche.png"))); // NOI18N
        pnelCrearPedido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sancocho.png"))); // NOI18N
        pnelCrearPedido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, 100));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Screenshot from 2024-12-08 03-40-19.png"))); // NOI18N
        pnelCrearPedido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 100, 130));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tilapia Frita.png"))); // NOI18N
        pnelCrearPedido.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 140));

        labelProductos1.setBackground(new java.awt.Color(255, 255, 255));
        labelProductos1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        labelProductos1.setText("Productos:");
        pnelCrearPedido.add(labelProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelProductos2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos2.setText("Fritos");
        pnelCrearPedido.add(labelProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        labelProductos3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos3.setText("Entradas");
        pnelCrearPedido.add(labelProductos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        labelProductos4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos4.setText("Sancochos");
        pnelCrearPedido.add(labelProductos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        labelProductos5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelProductos5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductos5.setText("Bebidas");
        pnelCrearPedido.add(labelProductos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        cbxFritos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxFritos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tilapia $35.000", "Tilapia $20.000" }));
        cbxFritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFritosActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxFritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        cbxBebidas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limonada Natu $8.000", "Limonada Cere $10.000", "Limonada Coco $10.000" }));
        cbxBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBebidasActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        cbxEspeciales.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxEspeciales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caz. camarón $35.000", "Caz. mariscos $35.000", " " }));
        cbxEspeciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecialesActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, -1));

        cbxSancocho.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbxSancocho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño $4.000", "Mediano $6.000", "Grande $8.000", " " }));
        cbxSancocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSancochoActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(cbxSancocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        cantBebidas.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        cantEntradas.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        cantSancocho.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantSancocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));

        cantEspeciales.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        cantFritos.setFocusCycleRoot(true);
        pnelCrearPedido.add(cantFritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        btnCrearPedido.setBackground(new java.awt.Color(255, 102, 0));
        btnCrearPedido.setFont(new java.awt.Font("Liberation Sans", 1, 26)); // NOI18N
        btnCrearPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPedido.setText("Crear ! ");
        btnCrearPedido.setBorder(null);
        btnCrearPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });
        pnelCrearPedido.add(btnCrearPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 130, 70));

        jTabbedPane1.addTab("Crear Pedido", pnelCrearPedido);

        Background.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnMesa1ActionPerformed

    private void cbxEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntradasActionPerformed

    private void cbxFritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFritosActionPerformed

    private void cbxBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBebidasActionPerformed

    private void cbxEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspecialesActionPerformed

    private void cbxSancochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSancochoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSancochoActionPerformed

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        //MeseroControl.crearPedido();
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    public JPanel getBackgroundPanel() {
        return Background;
    }

    public void setBackground(JPanel Background) {
        this.Background = Background;
    }

    public JSpinner getCantBebidas() {
        return cantBebidas;
    }

    public void setCantBebidas(JSpinner cantBebidas) {
        this.cantBebidas = cantBebidas;
    }

    public JSpinner getCantEntradas() {
        return cantEntradas;
    }

    public void setCantEntradas(JSpinner cantEntradas) {
        this.cantEntradas = cantEntradas;
    }

    public JSpinner getCantEspeciales() {
        return cantEspeciales;
    }

    public void setCantEspeciales(JSpinner cantEspeciales) {
        this.cantEspeciales = cantEspeciales;
    }

    public JSpinner getCantFritos() {
        return cantFritos;
    }

    public void setCantFritos(JSpinner cantFritos) {
        this.cantFritos = cantFritos;
    }

    public JSpinner getCantSancocho() {
        return cantSancocho;
    }

    public void setCantSancocho(JSpinner cantSancocho) {
        this.cantSancocho = cantSancocho;
    }

    public JComboBox<String> getCbxBebidas() {
        return cbxBebidas;
    }

    public void setCbxBebidas(JComboBox<String> cbxBebidas) {
        this.cbxBebidas = cbxBebidas;
    }

    public JComboBox<String> getCbxEntradas() {
        return cbxEntradas;
    }

    public void setCbxEntradas(JComboBox<String> cbxEntradas) {
        this.cbxEntradas = cbxEntradas;
    }

    public JComboBox<String> getCbxEspeciales() {
        return cbxEspeciales;
    }

    public void setCbxEspeciales(JComboBox<String> cbxEspeciales) {
        this.cbxEspeciales = cbxEspeciales;
    }

    public JComboBox<String> getCbxFritos() {
        return cbxFritos;
    }

    public void setCbxFritos(JComboBox<String> cbxFritos) {
        this.cbxFritos = cbxFritos;
    }

    public JComboBox<String> getCbxSancocho() {
        return cbxSancocho;
    }

    public void setCbxSancocho(JComboBox<String> cbxSancocho) {
        this.cbxSancocho = cbxSancocho;
    }

    public JButton getjButton1() {
        return btnCrearPedido;
    }

    public void setjButton1(JButton jButton1) {
        this.btnCrearPedido = jButton1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JLabel getLabelMesas() {
        return labelMesas;
    }

    public void setLabelMesas(JLabel labelMesas) {
        this.labelMesas = labelMesas;
    }

    public JLabel getLabelProductos() {
        return labelProductos;
    }

    public void setLabelProductos(JLabel labelProductos) {
        this.labelProductos = labelProductos;
    }

    public JLabel getLabelProductos1() {
        return labelProductos1;
    }

    public void setLabelProductos1(JLabel labelProductos1) {
        this.labelProductos1 = labelProductos1;
    }

    public JLabel getLabelProductos2() {
        return labelProductos2;
    }

    public void setLabelProductos2(JLabel labelProductos2) {
        this.labelProductos2 = labelProductos2;
    }

    public JLabel getLabelProductos3() {
        return labelProductos3;
    }

    public void setLabelProductos3(JLabel labelProductos3) {
        this.labelProductos3 = labelProductos3;
    }

    public JLabel getLabelProductos4() {
        return labelProductos4;
    }

    public void setLabelProductos4(JLabel labelProductos4) {
        this.labelProductos4 = labelProductos4;
    }

    public JLabel getLabelProductos5() {
        return labelProductos5;
    }

    public void setLabelProductos5(JLabel labelProductos5) {
        this.labelProductos5 = labelProductos5;
    }

    public JPanel getPnelCrearPedido() {
        return pnelCrearPedido;
    }

    public void setPnelCrearPedido(JPanel pnelCrearPedido) {
        this.pnelCrearPedido = pnelCrearPedido;
    }

    public JRadioButton getRdBtnMesa1() {
        return rdBtnMesa1;
    }

    public void setRdBtnMesa1(JRadioButton rdBtnMesa1) {
        this.rdBtnMesa1 = rdBtnMesa1;
    }

    public JRadioButton getRdBtnMesa2() {
        return rdBtnMesa2;
    }

    public void setRdBtnMesa2(JRadioButton rdBtnMesa2) {
        this.rdBtnMesa2 = rdBtnMesa2;
    }

    public JRadioButton getRdBtnMesa3() {
        return rdBtnMesa3;
    }

    public void setRdBtnMesa3(JRadioButton rdBtnMesa3) {
        this.rdBtnMesa3 = rdBtnMesa3;
    }

    public JRadioButton getRdBtnMesa4() {
        return rdBtnMesa4;
    }

    public void setRdBtnMesa4(JRadioButton rdBtnMesa4) {
        this.rdBtnMesa4 = rdBtnMesa4;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public JLabel getTituloCrearPedido() {
        return tituloCrearPedido;
    }

    public void setTituloCrearPedido(JLabel tituloCrearPedido) {
        this.tituloCrearPedido = tituloCrearPedido;
    }

    public JButton getBtnCrearPedido() {
        return btnCrearPedido;
    }

    public void setBtnCrearPedido(JButton btnCrearPedido) {
        this.btnCrearPedido = btnCrearPedido;
    }

    public ButtonGroup getBtnGrupo() {
        return btnGrupo;
    }

    public void setBtnGrupo(ButtonGroup btnGrupo) {
        this.btnGrupo = btnGrupo;
    }
    
    public int getIdMesaSeleccionada() {
        if (rdBtnMesa1.isSelected()) return 1;
        if (rdBtnMesa2.isSelected()) return 2;
        if (rdBtnMesa3.isSelected()) return 3;
        if (rdBtnMesa4.isSelected()) return 4;
        return -1; // Si no hay mesa seleccionada
    }
    public int getCantidadSeleccionada(String tipoProducto) {
        switch (tipoProducto) {
            case "Entradas":
                return (Integer) cantEntradas.getValue();
            case "Fritos":
                return (Integer) cantFritos.getValue();
            case "Bebidas":
                return (Integer) cantBebidas.getValue();
            case "Sancocho":
                return (Integer) cantSancocho.getValue();
            case "Especiales":
                return (Integer) cantEspeciales.getValue();
            default:
                return 0; // Si no hay producto seleccionado
        }
    }

    public String getProductoSeleccionado(String tipo) {
        switch (tipo) {
            case "Entradas":
                return (String) cbxEntradas.getSelectedItem();
            case "Fritos":
                return (String) cbxFritos.getSelectedItem();
            case "Bebidas":
                return (String) cbxBebidas.getSelectedItem();
            case "Sancocho":
                return (String) cbxSancocho.getSelectedItem();
            case "Especiales":
                return (String) cbxEspeciales.getSelectedItem();
            default:
                return null;
        }
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarVista(Pedido pedido) {
        double total = 0.0;
        for (Producto producto : pedido.getProductos()) {
        total += producto.getPrecio(); // Asumiendo que cada producto tiene un precio
        }

        lblTotal.setText("Total: " + total);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JSpinner cantBebidas;
    private javax.swing.JSpinner cantEntradas;
    private javax.swing.JSpinner cantEspeciales;
    private javax.swing.JSpinner cantFritos;
    private javax.swing.JSpinner cantSancocho;
    private javax.swing.JComboBox<String> cbxBebidas;
    private javax.swing.JComboBox<String> cbxEntradas;
    private javax.swing.JComboBox<String> cbxEspeciales;
    private javax.swing.JComboBox<String> cbxFritos;
    private javax.swing.JComboBox<String> cbxSancocho;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelMesas;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelProductos1;
    private javax.swing.JLabel labelProductos2;
    private javax.swing.JLabel labelProductos3;
    private javax.swing.JLabel labelProductos4;
    private javax.swing.JLabel labelProductos5;
    private javax.swing.JPanel pnelCrearPedido;
    private javax.swing.JRadioButton rdBtnMesa1;
    private javax.swing.JRadioButton rdBtnMesa2;
    private javax.swing.JRadioButton rdBtnMesa3;
    private javax.swing.JRadioButton rdBtnMesa4;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloCrearPedido;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnCrearPedido) {
            meseroControlador.crearPedido();
        }
    }
}
